// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgjpjqYN0pg-18uOD6Qyqs4pZg18wNcAg',
    appId: '1:246695301130:web:484730efc8f61f97360ff3',
    messagingSenderId: '246695301130',
    projectId: 'maps-308e2',
    authDomain: 'maps-308e2.firebaseapp.com',
    storageBucket: 'maps-308e2.appspot.com',
    measurementId: 'G-D95QYWN7KG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANn_E2TSE6LQ9Du1_fsdLVA_hOsvEAKOo',
    appId: '1:246695301130:android:d5d2d67e3daddde7360ff3',
    messagingSenderId: '246695301130',
    projectId: 'maps-308e2',
    storageBucket: 'maps-308e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD_KL7II19StU6MI8AIhPqcFv31AUcCNI',
    appId: '1:246695301130:ios:e5744f31cd2bc2dd360ff3',
    messagingSenderId: '246695301130',
    projectId: 'maps-308e2',
    storageBucket: 'maps-308e2.appspot.com',
    iosBundleId: 'com.example.flutterMaps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD_KL7II19StU6MI8AIhPqcFv31AUcCNI',
    appId: '1:246695301130:ios:672b3974617d9bdc360ff3',
    messagingSenderId: '246695301130',
    projectId: 'maps-308e2',
    storageBucket: 'maps-308e2.appspot.com',
    iosBundleId: 'com.example.flutterMaps.RunnerTests',
  );
}
